// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	common "github.com/ethereum/go-ethereum/common"
	mock "github.com/stretchr/testify/mock"

	pebble "github.com/cockroachdb/pebble"

	storage "github.com/onflow/flow-evm-gateway/storage"
)

// UserOperationIndexer is an autogenerated mock type for the UserOperationIndexer type
type UserOperationIndexer struct {
	mock.Mock
}

// GetTxHashByUserOpHash provides a mock function with given fields: userOpHash
func (_m *UserOperationIndexer) GetTxHashByUserOpHash(userOpHash common.Hash) (common.Hash, error) {
	ret := _m.Called(userOpHash)

	if len(ret) == 0 {
		panic("no return value specified for GetTxHashByUserOpHash")
	}

	var r0 common.Hash
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Hash) (common.Hash, error)); ok {
		return rf(userOpHash)
	}
	if rf, ok := ret.Get(0).(func(common.Hash) common.Hash); ok {
		r0 = rf(userOpHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(common.Hash)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Hash) error); ok {
		r1 = rf(userOpHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserOpReceipt provides a mock function with given fields: userOpHash
func (_m *UserOperationIndexer) GetUserOpReceipt(userOpHash common.Hash) (*storage.UserOperationReceipt, error) {
	ret := _m.Called(userOpHash)

	if len(ret) == 0 {
		panic("no return value specified for GetUserOpReceipt")
	}

	var r0 *storage.UserOperationReceipt
	var r1 error
	if rf, ok := ret.Get(0).(func(common.Hash) (*storage.UserOperationReceipt, error)); ok {
		return rf(userOpHash)
	}
	if rf, ok := ret.Get(0).(func(common.Hash) *storage.UserOperationReceipt); ok {
		r0 = rf(userOpHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*storage.UserOperationReceipt)
		}
	}

	if rf, ok := ret.Get(1).(func(common.Hash) error); ok {
		r1 = rf(userOpHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// StoreUserOpTxMapping provides a mock function with given fields: userOpHash, txHash, batch
func (_m *UserOperationIndexer) StoreUserOpTxMapping(userOpHash common.Hash, txHash common.Hash, batch *pebble.Batch) error {
	ret := _m.Called(userOpHash, txHash, batch)

	if len(ret) == 0 {
		panic("no return value specified for StoreUserOpTxMapping")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.Hash, common.Hash, *pebble.Batch) error); ok {
		r0 = rf(userOpHash, txHash, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// StoreUserOpReceipt provides a mock function with given fields: userOpHash, receipt, batch
func (_m *UserOperationIndexer) StoreUserOpReceipt(userOpHash common.Hash, receipt *storage.UserOperationReceipt, batch *pebble.Batch) error {
	ret := _m.Called(userOpHash, receipt, batch)

	if len(ret) == 0 {
		panic("no return value specified for StoreUserOpReceipt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(common.Hash, *storage.UserOperationReceipt, *pebble.Batch) error); ok {
		r0 = rf(userOpHash, receipt, batch)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserOperationIndexer creates a new instance of UserOperationIndexer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserOperationIndexer(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserOperationIndexer {
	mock := &UserOperationIndexer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

