// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	models "github.com/onflow/flow-evm-gateway/models"
)

// FeeParamsSubscriber is an autogenerated mock type for the FeeParamsSubscriber type
type FeeParamsSubscriber struct {
	mock.Mock
}

// Subscribe provides a mock function with given fields: ctx
func (_m *FeeParamsSubscriber) Subscribe(ctx context.Context) <-chan *models.FeeParamsEvents {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan *models.FeeParamsEvents
	if rf, ok := ret.Get(0).(func(context.Context) <-chan *models.FeeParamsEvents); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *models.FeeParamsEvents)
		}
	}

	return r0
}

// NewFeeParamsSubscriber creates a new instance of FeeParamsSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewFeeParamsSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *FeeParamsSubscriber {
	mock := &FeeParamsSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
